### ISSUE TITLE
ubuntu 16.04 install error

### ISSUE THREAD

**Issue by xgdgsc** [NoOne-hub/v2ray_client#24]
```
Exception:
Traceback (most recent call last):                                                                                                                                                           
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 377, in _make_request                                                                  
    httplib_response = conn.getresponse(buffering=True)                                                                                                                                      
TypeError: getresponse() got an unexpected keyword argument 'buffering'                                                                                                                      

During handling of the above exception, another exception occurred:                                                                                                                          

Traceback (most recent call last):                                                                                                                                                           
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 379, in _make_request                                                                  
    httplib_response = conn.getresponse()                                                                                                                                                    
  File "/usr/lib/python3.5/http/client.py", line 1213, in getresponse                                                                                                                        
    response.begin()                                                                                                                                                                         
  File "/usr/lib/python3.5/http/client.py", line 307, in begin                                                                                                                               
    version, status, reason = self._read_status()                                                                                                                                            
  File "/usr/lib/python3.5/http/client.py", line 268, in _read_status                                                                                                                        
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")                                                                                                                                 
  File "/usr/lib/python3.5/socket.py", line 575, in readinto                                                                                                                                 
    return self._sock.recv_into(b)                                                                                                                                                           
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into                                                                                                                                   
    return self.read(nbytes, buffer)                                                                                                                                                         
  File "/usr/lib/python3.5/ssl.py", line 791, in read                                                                                                                                        
    return self._sslobj.read(len, buffer)                                                                                                                                                    
  File "/usr/lib/python3.5/ssl.py", line 575, in read                                                                                                                                        
    v = self._sslobj.read(len, buffer)                                                                                                                                                       
socket.timeout: The read operation timed out                                                                                                                                                 

During handling of the above exception, another exception occurred:                                                                                                                          

Traceback (most recent call last):                                                                                                                                                           
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 560, in urlopen                                                                        
    body=body, headers=headers)                                                                                                                                                              
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 381, in _make_request                                                                  
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)                                                                                                                          
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 309, in _raise_timeout                                                                 
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)                                                                                                   
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)                                    

During handling of the above exception, another exception occurred:                                                                                                                          

Traceback (most recent call last):                                                                                                                                                           
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 209, in main                                                                                                                
    status = self.run(options, args)                                                                                                                                                         
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 317, in run                                                                                                            
    requirement_set.prepare_files(finder)                                                                                                                                                    
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 360, in prepare_files                                                                                                       
    ignore_dependencies=self.ignore_dependencies))                                                                                                                                           
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 577, in _prepare_file                                                                                                       
    session=self.session, hashes=hashes)                                                                                                                                                     
  File "/usr/lib/python3/dist-packages/pip/download.py", line 810, in unpack_url                                                                                                             
    hashes=hashes                                                                                                                                                                            
  File "/usr/lib/python3/dist-packages/pip/download.py", line 649, in unpack_http_url                                                                                                        
    hashes)                                                                                                                                                                                  
  File "/usr/lib/python3/dist-packages/pip/download.py", line 842, in _download_http_url                                                                                                     
    stream=True,                                                                                                                                                                             
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 480, in get                                                                                 
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 228, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

**Comment by xgdgsc** [comment]
pypi源的问题
